//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RemindersEntities : DbContext
    {
        public RemindersEntities()
            : base("name=RemindersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeesGroup> EmployeesGroups { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LookUpCategory> LookUpCategories { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<RemindersGroup> RemindersGroups { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    }
}
