//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> InternalID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Sort { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
    
        public virtual LookUpCategory LookUpCategory { get; set; }
        public virtual Lookup Lookups1 { get; set; }
        public virtual Lookup Lookup1 { get; set; }
    }
}
