//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemindersGroup
    {
        public int ID { get; set; }
        public int ReminderID { get; set; }
        public int GroupID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public int CreatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Reminder Reminder { get; set; }
    }
}
