//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appointment.Resource.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaids@sssprocess.com.
        /// </summary>
        public static string EmailSender {
            get {
                return ResourceManager.GetString("EmailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P@ssw0rd.
        /// </summary>
        public static string EmailSenderPassword {
            get {
                return ResourceManager.GetString("EmailSenderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string portnumber {
            get {
                return ResourceManager.GetString("portnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string RemindeBefore {
            get {
                return ResourceManager.GetString("RemindeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string SchdulerStartHour24 {
            get {
                return ResourceManager.GetString("SchdulerStartHour24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string SchdulerStartMinute {
            get {
                return ResourceManager.GetString("SchdulerStartMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.sssprocess.com.
        /// </summary>
        public static string smtpaddress {
            get {
                return ResourceManager.GetString("smtpaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish him a Happy Birthday!!.
        /// </summary>
        public static string TemplateBirthday {
            get {
                return ResourceManager.GetString("TemplateBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear all employees we have meeting Dont Forget it :D.
        /// </summary>
        public static string TemplateGeneral {
            get {
                return ResourceManager.GetString("TemplateGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string typeJob {
            get {
                return ResourceManager.GetString("typeJob", resourceCulture);
            }
        }
    }
}
